version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: booking_postgres_showcase
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: booking_db_showcase
      POSTGRES_USER: booking_user_showcase
      POSTGRES_PASSWORD: booking_password_showcase
    volumes:
      - postgres_data_showcase:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: booking_backend_showcase
    command: daphne -b 0.0.0.0 -p 8080 booking_project.asgi:application
    volumes:
      - ./backend:/app
      - media_volume:/app/booking_project/media
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://booking_user_showcase:booking_password_showcase@postgres:5432/booking_db_showcase
      - SECRET_KEY=django-insecure-dev-key-for-showcase-only
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: booking_redis
    ports:
      - "6379:6379"


  celery:
    build:
      context: ./backend
    container_name: booking_celery
    command: celery -A booking_project worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres


  celery_beat:
    build:
      context: ./backend
    container_name: booking_celery_beat
    command: celery -A booking_project beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres


  stripe_cli:
    image: stripe/stripe-cli:latest
    container_name: booking_stripe_cli
    command: listen --forward-to backend:8080/booking_api/webhook/stripe/ --api-key ${STRIPE_SECRET_KEY} --device-name local_docker_dev
    env_file:
      - .env
    volumes:
      - stripe_config:/root/.config/stripe
    depends_on:
      - backend



  frontend:
    build:
      context: ./frontend
    container_name: booking_frontend_showcase
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data_showcase:
  media_volume:
  stripe_config:

















