# Generated by Django 5.0.14 on 2026-09-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_day', models.DateField()),
                ('checkout_day', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='when unpaid booking expires', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('session_created', 'Session created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=32)),
                ('provider', models.CharField(choices=[('Stripe', 'stripe'), ('Yoomoney', 'yoomoney')], default='Stripe', max_length=255)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_reference', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('apartment', 'date')},
            },
        ),
    ]
